import type { ModuleId } from '@dc/config';
import type { PolicyOwner } from './owners.js';

/**
 * The policy register — Phase 0.9.
 *
 * `00-shared-contract.md:119` requires every unknown business value to live in
 * `PolicyRequirement` rather than in code.
 * [ADR-005](../../../docs/01-DECISIONS.md#adr-005) splits them on ownership:
 *
 *   **List A** — engineering-decidable now. Recorded as an approved version with
 *   `source: engineering_default` at bootstrap. Nothing waits on it.
 *
 *   **List B** — genuinely external. Stays `unresolved`, blocks activation of the affected
 *   capability, and needs a named person the project has to go and find.
 *
 * Every entry carries the `file:line` it was extracted from, and a test reads those lines
 * off disk. The register is derived from the 49 `assumption to verify` markers in the
 * specifications, with compound markers split into the discrete values behind them.
 *
 * Six markers are **conventions, not values** — `00-shared-contract.md:9`, `:123`, `:135`,
 * `19-…:3`, `:36` and `20-…:3` define how unknowns are recorded. They produce no entry,
 * and `19-…:133` explicitly holds dates, staffing and budget out of scope.
 */
export interface RegisterEntry {
  /** `policy.<module>.<name>` — namespaced so it can never collide with a capability. */
  readonly key: string;
  readonly module: ModuleId;
  /** Shown to the user beside `À confirmer`. */
  readonly label_fr: string;
  readonly list: 'A' | 'B';
  readonly owner: PolicyOwner;
  /** `file:line` in `specs/`. */
  readonly source: string;
  /** The question the owner must answer, in their language, not the schema's. */
  readonly question: string;
  /** What stays unavailable while this is unresolved. */
  readonly blocks: string;
  /** JSON Schema an approved value must satisfy. */
  readonly schema: Record<string, unknown>;
  /** List A only: the engineering default, recorded as approved at bootstrap. */
  readonly value?: unknown;
}

const int = (min?: number, max?: number) => ({
  type: 'integer',
  ...(min === undefined ? {} : { minimum: min }),
  ...(max === undefined ? {} : { maximum: max }),
});
const text = () => ({ type: 'string', minLength: 1 });
const codes = () => ({ type: 'array', items: { type: 'string', minLength: 1 }, minItems: 1 });
const bool = () => ({ type: 'boolean' });
/**
 * ISO-8601 duration. The date part and the time part are each optional, but at least one
 * component must be present — `PT15M` is valid and a pattern requiring a date part rejects
 * it. A schema that rejects its own default fails the first time a reviewer supersedes it.
 */
const duration = () => ({
  type: 'string',
  pattern: '^P(?!$)(\\d+Y)?(\\d+M)?(\\d+W)?(\\d+D)?(T(?!$)(\\d+H)?(\\d+M)?(\\d+S)?)?$',
});

export const POLICY_REGISTER: readonly RegisterEntry[] = [
  // ══ List A — engineering-decidable, approved at bootstrap ════════════════════════════

  {
    key: 'policy.platform.page_size_default',
    module: 'PL01',
    label_fr: 'Taille de page par défaut',
    list: 'A',
    owner: 'engineering',
    source: '00-shared-contract.md:101',
    question: 'How many rows does a list return when the caller does not ask?',
    blocks: 'Nothing. A default is needed before the first list endpoint.',
    schema: int(1, 200),
    value: 50,
  },
  {
    key: 'policy.platform.page_size_maximum',
    module: 'PL01',
    label_fr: 'Taille de page maximale',
    list: 'A',
    owner: 'engineering',
    source: '00-shared-contract.md:101',
    question: 'What is the largest page a caller may request?',
    blocks: 'Nothing.',
    schema: int(1, 1000),
    value: 200,
  },
  {
    key: 'policy.platform.cursor_ttl',
    module: 'PL01',
    label_fr: 'Durée de validité du curseur de pagination',
    list: 'A',
    owner: 'engineering',
    source: '00-shared-contract.md:101',
    question: 'How long does a pagination cursor stay valid? It binds filter, sort and scope.',
    blocks: 'Nothing.',
    schema: duration(),
    value: 'PT15M',
  },
  {
    key: 'policy.jobs.max_attempts',
    module: 'FD02',
    label_fr: 'Nombre maximal de tentatives par tâche',
    list: 'A',
    owner: 'engineering',
    source: '19-security-operations-delivery.md:43',
    question: 'How many times is a failing job retried before it is marked failed?',
    blocks:
      'Nothing — but the worker currently runs on a provisional constant, which this replaces.',
    schema: int(1, 20),
    value: 5,
  },
  {
    key: 'policy.jobs.backoff_seconds',
    module: 'FD02',
    label_fr: 'Temporisation initiale entre tentatives',
    list: 'A',
    owner: 'engineering',
    source: '19-security-operations-delivery.md:43',
    question: 'Base of the exponential backoff between job attempts, in seconds.',
    blocks: 'Nothing.',
    schema: int(1, 3600),
    value: 10,
  },
  {
    key: 'policy.jobs.lease_seconds',
    module: 'FD02',
    label_fr: 'Durée du bail de traitement',
    list: 'A',
    owner: 'engineering',
    source: '19-security-operations-delivery.md:43',
    question:
      'How long may a worker hold a job before the lease expires and it returns to the queue?',
    blocks: 'Nothing.',
    schema: int(10, 3600),
    value: 60,
  },
  {
    key: 'policy.document.max_bytes',
    module: 'FD02',
    label_fr: 'Taille maximale d’un document',
    list: 'A',
    owner: 'engineering',
    source: '02-FD02-evidence.md:33',
    question: 'Largest single upload accepted, in bytes.',
    blocks: 'Nothing — a limit is needed before the first upload endpoint.',
    schema: int(1, 1073741824),
    value: 52428800,
  },
  {
    key: 'policy.document.chunk_bytes',
    module: 'FD02',
    label_fr: 'Taille de segment de téléversement',
    list: 'A',
    owner: 'engineering',
    source: '20-data-api-contract-details.md:125',
    question: 'Chunk size for a resumable upload session.',
    blocks: 'Nothing.',
    schema: int(65536, 104857600),
    value: 8388608,
  },
  {
    key: 'policy.document.base_mime_allowlist',
    module: 'FD02',
    label_fr: 'Formats de document acceptés',
    list: 'A',
    owner: 'engineering',
    source: '02-FD02-evidence.md:33',
    question:
      'The PDF, image and structured formats the spec names outright. Anything beyond them is a separate, reviewed decision.',
    blocks: 'Nothing.',
    schema: codes(),
    value: [
      'application/pdf',
      'image/jpeg',
      'image/png',
      'image/tiff',
      'text/csv',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    ],
  },
  {
    key: 'policy.api.request_timeout_seconds',
    module: 'DF06',
    label_fr: 'Délai d’expiration des appels sortants',
    list: 'A',
    owner: 'engineering',
    source: '16-DF06-api-integrations.md:42',
    question: 'How long an outbound adapter call may run before it is abandoned.',
    blocks: 'Nothing.',
    schema: int(1, 300),
    value: 30,
  },
  {
    key: 'policy.api.replay_window_seconds',
    module: 'DF06',
    label_fr: 'Fenêtre anti-rejeu des webhooks',
    list: 'A',
    owner: 'engineering',
    source: '16-DF06-api-integrations.md:42',
    question: 'How old a signed webhook may be before it is rejected as a replay.',
    blocks: 'Nothing.',
    schema: int(30, 3600),
    value: 300,
  },
  {
    key: 'policy.api.synthetic_rate_limit',
    module: 'DF06',
    label_fr: 'Limite de débit pour les essais synthétiques',
    list: 'A',
    owner: 'engineering',
    source: '16-DF06-api-integrations.md:42',
    question:
      'Requests per minute per principal, for synthetic testing only. The production limit is a service-owner value.',
    blocks: 'Nothing. Production rate limits are `policy.platform.rate_limits`.',
    schema: int(1, 100000),
    value: 600,
  },
  {
    key: 'policy.platform.accessibility_standard',
    module: 'PL01',
    label_fr: 'Norme d’accessibilité retenue',
    list: 'A',
    owner: 'engineering',
    source: '17-PL01-ux.md:40',
    question:
      'The exact standard and version recorded at bootstrap as the technical compliance target. `:40` asks for it to be recorded, not negotiated — publishing a conformance claim is a separate, reviewed act.',
    blocks: 'Nothing. Functional keyboard access is mandatory now regardless.',
    schema: text(),
    value: 'WCAG 2.2 AA',
  },
  {
    key: 'policy.assistant.scan_schedule',
    module: 'DF05',
    label_fr: 'Cadence des analyses de l’assistant',
    list: 'A',
    owner: 'engineering',
    source: '15-DF05-advisory.md:34',
    question: 'How often a scheduled scan runs. Overlapping same-scope runs are prevented.',
    blocks: 'Nothing — DF05 activation is gated on its own provider approval.',
    schema: text(),
    value: '0 3 * * *',
  },
  {
    key: 'policy.assistant.scan_timeout_seconds',
    module: 'DF05',
    label_fr: 'Durée maximale d’une analyse',
    list: 'A',
    owner: 'engineering',
    source: '15-DF05-advisory.md:34',
    question: 'How long a single scan may run before it is abandoned and reported as skipped.',
    blocks: 'Nothing.',
    schema: int(30, 86400),
    value: 900,
  },

  // ══ List B — external. Stays unresolved; blocks what it names. ════════════════════════

  // ── Regulatory reviewer ──────────────────────────────────────────────────────────────
  {
    key: 'policy.regime.applicability',
    module: 'CR01',
    label_fr: 'Régimes douaniers pris en charge',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '04-CR01-dossiers.md:58',
    question:
      'Which customs regimes this installation supports, and the conditions under which each applies.',
    blocks: 'Declaration readiness, official preparation approval, every regime-dependent rule.',
    schema: codes(),
  },
  {
    key: 'policy.regime.document_lists',
    module: 'CR01',
    label_fr: 'Documents exigibles par régime',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '04-CR01-dossiers.md:58',
    question:
      'Which documents each regime and operation requires, and when each becomes mandatory.',
    blocks: 'Readiness scoring, the blocker list, declaration approval.',
    schema: { type: 'object', additionalProperties: codes() },
  },
  {
    key: 'policy.valuation.formula',
    module: 'CR01',
    label_fr: 'Formules de valeur en douane',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '04-CR01-dossiers.md:58',
    question: 'How customs value is computed, per regime and incoterm.',
    blocks: 'Every declaration calculation. Draft capture stays available.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.tariff.rates',
    module: 'CR01',
    label_fr: 'Droits et taxes applicables',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '04-CR01-dossiers.md:58',
    question: 'Duty and tax rates by tariff heading, with their effective dates.',
    blocks: 'Duty calculation, declaration approval.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.regime.event_semantics',
    module: 'CR01',
    label_fr: 'Sémantique des événements officiels',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '04-CR01-dossiers.md:58',
    question:
      'What each official event means for the dossier — which one starts a clock, which one closes an obligation.',
    blocks: 'Deadline computation, external state interpretation.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.dossier.required_fields',
    module: 'CR01',
    label_fr: 'Champs obligatoires par flux',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '04-CR01-dossiers.md:58',
    question: 'Which fields each workflow requires before submission.',
    blocks: 'Submission validation. Draft capture stays available.',
    schema: { type: 'object', additionalProperties: codes() },
  },
  {
    key: 'policy.red.eligibility',
    module: 'CR04',
    label_fr: 'Régimes économiques autorisés',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '07-CR04-red.md:59',
    question: 'Which economic regimes this operator may use, and under what conditions.',
    blocks: 'RED posting, project activation.',
    schema: codes(),
  },
  {
    key: 'policy.red.dispositions',
    module: 'CR04',
    label_fr: 'Apurements autorisés',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '07-CR04-red.md:59',
    question: 'Which discharge routes are permitted for each regime.',
    blocks: 'Ledger discharge, RED closure.',
    schema: codes(),
  },
  {
    key: 'policy.red.aggregation_basis',
    module: 'CR04',
    label_fr: 'Base d’agrégation des soldes',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '07-CR04-red.md:59',
    question:
      'At what level balances aggregate — per lot, per heading, per project — since it changes every reported figure.',
    blocks: 'Balance reporting, discharge eligibility.',
    schema: text(),
  },
  {
    key: 'policy.deadline.periods',
    module: 'CR05',
    label_fr: 'Délais légaux et prorogations',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '08-CR05-obligations.md:47',
    question:
      'The statutory period for each obligation, what may extend it, and by how much. `Unknown is not today` — a missing period blocks rather than defaults.',
    blocks: 'Due-date computation. `DUE_DATE_UNKNOWN` until resolved.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.calendar.policy',
    module: 'CR05',
    label_fr: 'Calendriers de calcul des délais',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '08-CR05-obligations.md:47',
    question:
      'Working days, public holidays, inclusive boundaries and partial-period rule. A missing calendar is not weekdays.',
    blocks: 'Every deadline. Shared with the commercial reviewer for contract clocks.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.obligation.alert_thresholds',
    module: 'CR05',
    label_fr: 'Seuils d’alerte des échéances',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '08-CR05-obligations.md:47',
    question: 'How far ahead each obligation type raises an alert, and what makes one critical.',
    blocks: 'Deadline alerting. The list still shows real dates.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.rule.parameters',
    module: 'DF04',
    label_fr: 'Paramètres numériques des règles',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '14-DF04-rules.md:25',
    question:
      'Every numeric parameter an approved rule effect consumes — periods, scales, thresholds.',
    blocks: 'Rule activation. A rule may be drafted and reviewed without them.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.extraction.legal_validation',
    module: 'DF01',
    label_fr: 'Règles de validation légale des extractions',
    list: 'B',
    owner: 'regulatory_reviewer',
    source: '11-DF01-readiness.md:32',
    question: 'Which extracted fields carry legal weight, and what validates them.',
    blocks: 'Applying an extraction to an official field. Manual entry stays available.',
    schema: { type: 'object' },
  },

  // ── Finance reviewer ─────────────────────────────────────────────────────────────────
  {
    key: 'policy.invoice.numbering',
    module: 'CR02',
    label_fr: 'Numérotation des factures',
    list: 'B',
    owner: 'finance_reviewer',
    source: '20-data-api-contract-details.md:37',
    question: 'Series format, reset policy, timezone and effective date for invoice numbers.',
    blocks: 'Invoice issue. Cost capture and drafting ship without it.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.invoice.gap_treatment',
    module: 'CR02',
    label_fr: 'Traitement des ruptures de séquence',
    list: 'B',
    owner: 'finance_reviewer',
    source: '05-CR02-finance.md:34',
    question:
      'What the mandated treatment is when an issue transaction fails and leaves a gap in the series.',
    blocks: 'Nothing directly — but the runbook cannot be written without it.',
    schema: text(),
  },
  {
    key: 'policy.invoice.tax',
    module: 'CR02',
    label_fr: 'Règles de TVA à la facturation',
    list: 'B',
    owner: 'finance_reviewer',
    source: '04-CR01-dossiers.md:58',
    question: 'Tax rates and their applicability rules per service and client type.',
    blocks: 'Invoice issue.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.invoice.rounding',
    module: 'CR02',
    label_fr: 'Arrondi des montants facturés',
    list: 'B',
    owner: 'finance_reviewer',
    source: '20-data-api-contract-details.md:3',
    question: 'Scale and rounding mode, and at which step of the calculation it is applied.',
    blocks: 'Invoice issue. Rounding never comes from a default.',
    schema: {
      type: 'object',
      properties: { scale: int(0, 8), mode: text() },
      required: ['scale', 'mode'],
    },
  },
  {
    key: 'policy.invoice.credit_note',
    module: 'CR02',
    label_fr: 'Politique des avoirs',
    list: 'B',
    owner: 'finance_reviewer',
    source: '05-CR02-finance.md:34',
    question: 'When a credit note is permitted, and how it references the invoice it corrects.',
    blocks: 'The correction command is unavailable until this is approved.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.currency.scale',
    module: 'FD03',
    label_fr: 'Précision par devise',
    list: 'B',
    owner: 'finance_reviewer',
    source: '00-shared-contract.md:49',
    question: 'Decimal scale and rounding for each currency in use.',
    blocks: 'Any monetary calculation in that currency.',
    schema: { type: 'object', additionalProperties: int(0, 8) },
  },
  {
    key: 'policy.currency.fx_source',
    module: 'FD03',
    label_fr: 'Source des taux de change',
    list: 'B',
    owner: 'finance_reviewer',
    source: '04-CR01-dossiers.md:58',
    question:
      'Which published rate is authoritative, and on which date it is read. A missing rate is not parity.',
    blocks: 'Every conversion. No conversion without an explicit FX version.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.finance.revenue_recognition',
    module: 'CR02',
    label_fr: 'Base de reconnaissance du revenu',
    list: 'B',
    owner: 'finance_reviewer',
    source: '05-CR02-finance.md:40',
    question: 'When service revenue is recognized, and how pass-through is excluded symmetrically.',
    blocks: 'The margin view returns unavailable with its components rather than a figure.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.finance.cost_allocation',
    module: 'CR02',
    label_fr: 'Répartition des coûts partagés',
    list: 'B',
    owner: 'finance_reviewer',
    source: '05-CR02-finance.md:40',
    question: 'How a cost spanning several dossiers is attributed.',
    blocks: 'Margin per dossier.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.guarantee.release_policy',
    module: 'CR05',
    label_fr: 'Conditions de mainlevée des garanties',
    list: 'B',
    owner: 'finance_reviewer',
    source: '08-CR05-obligations.md:47',
    question:
      'What evidence releases a guarantee, and what a partial release requires. A bank confirmation is required and cannot be inferred.',
    blocks: 'Guarantee release. Balances remain visible.',
    schema: { type: 'object' },
  },

  // ── Commercial and transport reviewer ────────────────────────────────────────────────
  {
    key: 'policy.carrier.free_time',
    module: 'DF02',
    label_fr: 'Franchises accordées par transporteur',
    list: 'B',
    owner: 'commercial_reviewer',
    source: '12-DF02-delay-costs.md:5',
    question:
      'Free-time period per carrier, terminal and container type, with the event that starts the clock.',
    blocks: 'Every delay-cost estimate. Events are still tracked.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.carrier.tiers',
    module: 'DF02',
    label_fr: 'Barèmes de surestaries et de détention',
    list: 'B',
    owner: 'commercial_reviewer',
    source: '12-DF02-delay-costs.md:5',
    question: 'Tier boundaries and rates, and how overlapping charges combine.',
    blocks: 'Cost estimation. No estimate without complete approved inputs.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.transport.commercial_deadlines',
    module: 'CR03',
    label_fr: 'Délais commerciaux de transport',
    list: 'B',
    owner: 'commercial_reviewer',
    source: '06-CR03-transport.md:53',
    question: 'Return terms, release validity and the deadlines each carrier contract imposes.',
    blocks: 'Return-outstanding alerts and readiness exceptions.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.notification.reminder_cadence',
    module: 'CR06',
    label_fr: 'Cadence des relances client',
    list: 'B',
    owner: 'commercial_reviewer',
    source: '09-CR06-client-portal.md:34',
    question: 'How often a pending client action is chased. No invented cadence.',
    blocks: 'Automatic reminders. A request is still visible in the portal.',
    schema: { type: 'object' },
  },

  // ── Production and RED reviewer ──────────────────────────────────────────────────────
  {
    key: 'policy.bom.yields',
    module: 'DF03',
    label_fr: 'Rendements de nomenclature',
    list: 'B',
    owner: 'production_red_reviewer',
    source: '13-DF03-production.md:5',
    question: 'Expected yield per BOM, and the tolerance beyond which a variance needs review.',
    blocks: 'Production reconciliation. Movements are still recorded.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.production.exception_treatment',
    module: 'DF03',
    label_fr: 'Traitement des écarts de production',
    list: 'B',
    owner: 'production_red_reviewer',
    source: '13-DF03-production.md:5',
    question:
      'Permitted treatment of wastage, subcontracting and returns. An unsupported treatment stays unresolved rather than being approximated.',
    blocks: 'Customs adjustment from a production variance. No automatic adjustment either way.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.unit.precision',
    module: 'FD03',
    label_fr: 'Précision et conversion des unités',
    list: 'B',
    owner: 'production_red_reviewer',
    source: '07-CR04-red.md:59',
    question: 'Decimal precision per unit and the approved conversion factors between them.',
    blocks: 'Mixed-unit allocation and RED posting.',
    schema: { type: 'object' },
  },

  // ── Security and privacy owner ───────────────────────────────────────────────────────
  {
    key: 'policy.identity.session_duration',
    module: 'FD01',
    label_fr: 'Durée des sessions',
    list: 'B',
    owner: 'privacy_owner',
    source: '01-FD01-identity.md:45',
    question:
      'Idle and absolute session lifetimes. There is no production fallback to an unlimited session.',
    blocks: 'Production login activation.',
    schema: {
      type: 'object',
      properties: { idle: duration(), absolute: duration() },
      required: ['idle', 'absolute'],
    },
  },
  {
    key: 'policy.identity.assurance',
    module: 'FD01',
    label_fr: 'Niveaux d’assurance requis',
    list: 'B',
    owner: 'privacy_owner',
    source: '19-security-operations-delivery.md:10',
    question:
      'Which operations require re-authentication or stronger assurance, and how long that assurance lasts.',
    blocks: 'Privileged administration, confidential export, approval actions in production.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.privacy.retention',
    module: 'FD02',
    label_fr: 'Durées de conservation',
    list: 'B',
    owner: 'privacy_owner',
    source: '19-security-operations-delivery.md:28',
    question:
      'Retention duration per data category, with its lawful basis. Deletion cannot guess a duration.',
    blocks: 'Production storage activation and every purge.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.privacy.tombstone',
    module: 'FD02',
    label_fr: 'Contenu des enregistrements résiduels',
    list: 'B',
    owner: 'privacy_owner',
    source: '02-FD02-evidence.md:39',
    question: 'The minimum lawful content of a tombstone left behind by an erasure.',
    blocks: 'Purge execution.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.privacy.backup_deletion',
    module: 'FD02',
    label_fr: 'Obligations de suppression dans les sauvegardes',
    list: 'B',
    owner: 'privacy_owner',
    source: '02-FD02-evidence.md:39',
    question: 'What an erasure obliges in backups, and within what window.',
    blocks: 'Closing an erasure request.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.privacy.request_deadlines',
    module: 'FD02',
    label_fr: 'Délais de traitement des demandes',
    list: 'B',
    owner: 'privacy_owner',
    source: '19-security-operations-delivery.md:28',
    question: 'The statutory deadline for answering an access, rectification or erasure request.',
    blocks: 'Privacy request SLAs and their alerting.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.privacy.transfer_formalities',
    module: 'PL02',
    label_fr: 'Formalités de transfert hors du Maroc',
    list: 'B',
    owner: 'privacy_owner',
    source: '19-security-operations-delivery.md:24',
    question:
      'The applicable CNDP process for any hosting, processing or AI destination outside Morocco. Vendor encryption is not an answer to this.',
    blocks: 'Any non-Moroccan hosting or AI provider.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.ai.destination',
    module: 'DF05',
    label_fr: 'Destinations de traitement par IA',
    list: 'B',
    owner: 'privacy_owner',
    source: '19-security-operations-delivery.md:24',
    question: 'Approved provider, region, purpose, data categories and legal basis, per use.',
    blocks: 'Every DF01 and DF05 capability.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.ai.retention',
    module: 'DF05',
    label_fr: 'Conservation chez le fournisseur de modèle',
    list: 'B',
    owner: 'privacy_owner',
    source: '15-DF05-advisory.md:34',
    question: 'What the provider retains, for how long, and whether it trains on it.',
    blocks: 'DF05 activation.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.document.active_content',
    module: 'FD02',
    label_fr: 'Traitement des fichiers à contenu actif',
    list: 'B',
    owner: 'privacy_owner',
    source: '02-FD02-evidence.md:33',
    question:
      'Whether macro-bearing or active-content files are accepted at all, and under what control.',
    blocks: 'Nothing — they are refused until separately approved.',
    schema: bool(),
  },
  {
    key: 'policy.offline.attachment_policy',
    module: 'PL01',
    label_fr: 'Stockage hors ligne sur appareil partagé',
    list: 'B',
    owner: 'privacy_owner',
    source: '17-PL01-ux.md:24',
    question:
      'Whether attachments may be stored offline, for how long, and what a shared device changes.',
    blocks:
      'Offline attachment caching. In-memory drafts work now, and the UI says they are lost on close.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.incident.notification',
    module: 'PL02',
    label_fr: 'Destinataires et obligations de notification',
    list: 'B',
    owner: 'privacy_owner',
    source: '19-security-operations-delivery.md:85',
    question:
      'Who is told about an incident, within what deadline, and what the legal notification duty is.',
    blocks: 'Any externally addressed automatic message. Runbooks still record and contain.',
    schema: { type: 'object' },
  },

  // ── Integration owner ────────────────────────────────────────────────────────────────
  {
    key: 'policy.exchange.schemas',
    module: 'CR07',
    label_fr: 'Schémas des fichiers d’échange',
    list: 'B',
    owner: 'integration_owner',
    source: '10-CR07-reconciliation.md:5',
    question: 'The real file formats and acknowledgement contracts of each exchange partner.',
    blocks: 'Any claim of an official connection. Synthetic fixtures and manual evidence work now.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.integration.contracts',
    module: 'DF06',
    label_fr: 'Contrats d’accès aux systèmes officiels',
    list: 'B',
    owner: 'integration_owner',
    source: '16-DF06-api-integrations.md:31',
    question:
      'Documented access, credentials, schemas and acknowledgement semantics for PortNet, BADR or any official system. No invented API, no browser bypass.',
    blocks: 'Every live adapter. File and manual evidence is the route until then.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.integration.signature_scheme',
    module: 'DF06',
    label_fr: 'Schéma de signature des webhooks',
    list: 'B',
    owner: 'integration_owner',
    source: '16-DF06-api-integrations.md:42',
    question: 'How an inbound event is authenticated, and how its unique event id is formed.',
    blocks: 'Live ingestion stays disabled without it.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.migration.source_formats',
    module: 'FD03',
    label_fr: 'Formats des données à reprendre',
    list: 'B',
    owner: 'integration_owner',
    source: '03-FD03-migration.md:41',
    question: 'The real source formats and the true opening balances to migrate.',
    blocks: 'Migration commit. Synthetic CSV fixtures are product test formats, not imports.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.notification.destinations',
    module: 'CR06',
    label_fr: 'Canaux et destinations de notification',
    list: 'B',
    owner: 'integration_owner',
    source: '09-CR06-client-portal.md:34',
    question:
      'Approved SMTP or provider, sender identity and destinations. WhatsApp and SMS are not silently installed.',
    blocks: 'External email and messaging. The in-app channel is the default and works now.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.mailbox.contracts',
    module: 'DF01',
    label_fr: 'Accès aux boîtes mail sources',
    list: 'B',
    owner: 'integration_owner',
    source: '11-DF01-readiness.md:32',
    question: 'Mailbox provider contract, credentials and the confidence threshold for routing.',
    blocks: 'Automatic mail routing. Manual entry and routing work now.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.production.erp_contracts',
    module: 'DF03',
    label_fr: 'Contrats ERP de production',
    list: 'B',
    owner: 'integration_owner',
    source: '13-DF03-production.md:5',
    question: 'Source ERP schemas and event semantics for production movements.',
    blocks: 'Automatic production import. Manual submission works now.',
    schema: { type: 'object' },
  },

  // ── Service owner ────────────────────────────────────────────────────────────────────
  {
    key: 'policy.nfr.api_latency',
    module: 'PL02',
    label_fr: 'Objectif de latence API',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:42',
    question:
      'Target percentiles per named operation, under a declared dataset and concurrency. `nfr.api_latency`.',
    blocks: 'Production readiness. Measurement runs now; it cannot be marked passed.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.nfr.ui_latency',
    module: 'PL02',
    label_fr: 'Objectif de latence d’interaction',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:42',
    question: 'Browser interaction latency target per named operation. `nfr.ui_latency`.',
    blocks: 'Production readiness.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.nfr.job_latency',
    module: 'PL02',
    label_fr: 'Objectif de latence des traitements',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:43',
    question:
      'Queued-to-start and start-to-terminal targets by job type, and the backlog alert level. `nfr.job_latency`.',
    blocks: 'Production readiness.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.nfr.availability',
    module: 'PL02',
    label_fr: 'Objectif de disponibilité',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:44',
    question:
      'Eligible service window, what counts as a successful journey, maintenance treatment, support coverage. `nfr.availability`. No uptime claim before agreement and measurement.',
    blocks: 'Any availability commitment.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.nfr.rpo',
    module: 'PL02',
    label_fr: 'Perte de données maximale admissible',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:45',
    question: 'How much data the organization accepts losing. `nfr.rpo`.',
    blocks: 'Backup schedule design and production readiness.',
    schema: duration(),
  },
  {
    key: 'policy.nfr.rto',
    module: 'PL02',
    label_fr: 'Délai de reprise maximal',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:45',
    question: 'How long a full restore may take. `nfr.rto`.',
    blocks: 'Production readiness. The restore rehearsal runs regardless.',
    schema: duration(),
  },
  {
    key: 'policy.backup.schedule',
    module: 'PL02',
    label_fr: 'Fréquence, rétention et lieu des sauvegardes',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:81',
    question:
      'Backup frequency, retention, storage location and who holds the recovery keys. Follows from the RPO above.',
    blocks: 'Production readiness.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.nfr.capacity',
    module: 'PL02',
    label_fr: 'Capacité cible',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:46',
    question:
      'Dossier, document and ledger volumes, concurrent users, upload and export sizes. `nfr.capacity`. No guessed client count or storage quota.',
    blocks: 'Capacity testing sign-off and infrastructure sizing.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.platform.rate_limits',
    module: 'PL02',
    label_fr: 'Limites de débit en production',
    list: 'B',
    owner: 'service_owner',
    source: '16-DF06-api-integrations.md:42',
    question: 'Production request limits per principal and per endpoint class.',
    blocks: 'Production readiness. The synthetic limit above covers testing.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.platform.browser_matrix',
    module: 'PL01',
    label_fr: 'Navigateurs et appareils pris en charge',
    list: 'B',
    owner: 'service_owner',
    source: '17-PL01-ux.md:40',
    question: 'Which browsers, versions and devices are supported, and which are merely tolerated.',
    blocks: 'The published support commitment. Development targets current evergreen browsers.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.platform.assistive_technologies',
    module: 'PL01',
    label_fr: 'Technologies d’assistance prises en charge',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:47',
    question:
      'Which screen readers and assistive technologies are tested against. Conformance is not published without review.',
    blocks: 'Any published accessibility conformance claim.',
    schema: codes(),
  },
  {
    key: 'policy.platform.rtl_activation',
    module: 'PL01',
    label_fr: 'Activation de l’arabe et du sens RTL',
    list: 'B',
    owner: 'service_owner',
    source: '17-PL01-ux.md:34',
    question:
      'Whether Arabic is released, and who supplies the reviewed copy. The architecture is prepared; no untranslated screen ships.',
    blocks: 'Arabic release only. French is the released language.',
    schema: bool(),
  },
  {
    key: 'policy.license.terms',
    module: 'PL02',
    label_fr: 'Conditions de licence et de facturation',
    list: 'B',
    owner: 'service_owner',
    source: '18-PL02-launch-operations.md:36',
    question: 'Pricing, billing basis, ceilings and contractual limits.',
    blocks: 'Usage display shows measured units and known cost, never a price.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.license.signature',
    module: 'PL02',
    label_fr: 'Format signé et rotation des clés de licence',
    list: 'B',
    owner: 'service_owner',
    source: '20-data-api-contract-details.md:113',
    question: 'Signed licence format, issuer and key-rotation contract.',
    blocks: 'Module and licence enforcement stays unconfigured until supplied.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.assistant.token_ceiling',
    module: 'DF05',
    label_fr: 'Plafond de consommation de l’assistant',
    list: 'B',
    owner: 'service_owner',
    source: '15-DF05-advisory.md:34',
    question: 'Token or cost ceiling per period, and what happens when it is reached.',
    blocks: 'DF05 activation. A budget may stop optional work only once approved.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.platform.topology',
    module: 'PL02',
    label_fr: 'Topologie de déploiement approuvée',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:65',
    question:
      'Whether a single-host install meets this organization’s availability and recovery requirements.',
    blocks: 'Production deployment sign-off.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.platform.hosting',
    module: 'PL02',
    label_fr: 'Hébergeur et dimensionnement',
    list: 'B',
    owner: 'service_owner',
    source: '00-shared-contract.md:36',
    question:
      'Hosting provider, region and infrastructure sizing. Region interacts with CNDP above.',
    blocks: 'Production deployment.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.ops.alert_routing',
    module: 'PL02',
    label_fr: 'Routage et escalade des alertes',
    list: 'B',
    owner: 'service_owner',
    source: '19-security-operations-delivery.md:50',
    question: 'Who receives which alert, and how escalation works outside business hours.',
    blocks: 'Operational readiness. Alerts are still raised and logged.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.approval.small_org_subset',
    module: 'FD02',
    label_fr: 'Périmètre du mode « petite organisation »',
    list: 'B',
    owner: 'service_owner',
    source: 'docs/01-DECISIONS.md#adr-002',
    question:
      'Which action families a submitter may approve under `small_org_documented`, who is eligible, and what reason must be recorded. Coined by this project — the specs defer the alternative approval policy without naming it.',
    blocks:
      '`small_org_documented` refuses to run. `independent_reviewer` is the production default.',
    schema: { type: 'object' },
  },
  {
    key: 'policy.identity.role_bundles',
    module: 'FD01',
    label_fr: 'Capacités attachées à chaque rôle',
    list: 'B',
    owner: 'privacy_owner',
    source: 'docs/01-DECISIONS.md#adr-011',
    question:
      'Which capabilities each of the sixteen roles holds. The specs call roles fixed capability bundles and never enumerate them; 35 of 121 capabilities are grounded in module prose and 86 are not.',
    blocks:
      'Every unassigned capability denies by default. Nothing is silently granted, but a role may be unable to do its job.',
    schema: { type: 'object' },
  },
] as const;

export const LIST_A = POLICY_REGISTER.filter((e) => e.list === 'A');
export const LIST_B = POLICY_REGISTER.filter((e) => e.list === 'B');

export const entriesForOwner = (owner: PolicyOwner): readonly RegisterEntry[] =>
  POLICY_REGISTER.filter((e) => e.owner === owner);

export const registerEntry = (key: string): RegisterEntry | undefined =>
  POLICY_REGISTER.find((e) => e.key === key);
